/*
 * Don't go off selling software that uses this.
 */
package lebrigand.core.ui;

import javax.swing.border.TitledBorder;
import lebrigand.core.BotManager;

/**
 *
 * @author brian
 */
public class NewLeBrigandFrame extends javax.swing.JFrame {
    private final BotManager botManager;
    
    /**
     * Creates new form NewLeBrigandFrame
     * @param botManager The BotManager instance to use to populate the GUI
     */
    public NewLeBrigandFrame(BotManager botManager) {
        this.botManager = botManager;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        tabPane = new javax.swing.JTabbedPane();
        controlPanel = new javax.swing.JPanel();
        finalStatusLabel = new javax.swing.JLabel();
        statusPanel = new javax.swing.JPanel();
        finalLeBrigandUptimeLabel = new javax.swing.JLabel();
        leBrigandUptimeLabel = new javax.swing.JLabel();
        finalCurrentBotLabel = new javax.swing.JLabel();
        currentBotLabel = new javax.swing.JLabel();
        finalBotUptimeLabel = new javax.swing.JLabel();
        currentBotUptime = new javax.swing.JLabel();
        pauseBotButton = new javax.swing.JButton();
        stopBotButton = new javax.swing.JButton();
        finalAvailableBotsLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        debuggingPanel = new javax.swing.JPanel();
        logScrollPane = new javax.swing.JScrollPane();
        logTextPane = new javax.swing.JTextPane();
        debugOptsScrollPane = new javax.swing.JScrollPane();
        debugOptsPanel = new javax.swing.JPanel();
        finalLogLevelLabel = new javax.swing.JLabel();
        logLevelComboBox = new javax.swing.JComboBox<>();
        showDebugOverlayCheckBox = new javax.swing.JCheckBox();
        commandTextField = new javax.swing.JTextField();
        executeCommandButton = new javax.swing.JButton();
        aboutPanel = new javax.swing.JPanel();
        finalAppNameLabel = new javax.swing.JLabel();
        finalVersionLabel = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 600));
        setSize(new java.awt.Dimension(400, 600));

        finalStatusLabel.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        finalStatusLabel.setText("Status");

        statusPanel.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        statusPanel.setLayout(new java.awt.GridLayout(4, 2, 10, 0));

        finalLeBrigandUptimeLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        finalLeBrigandUptimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        finalLeBrigandUptimeLabel.setText("LeBrigand Uptime");
        statusPanel.add(finalLeBrigandUptimeLabel);

        leBrigandUptimeLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        leBrigandUptimeLabel.setText("00:00:00");
        statusPanel.add(leBrigandUptimeLabel);

        finalCurrentBotLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        finalCurrentBotLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        finalCurrentBotLabel.setText("Current Bot");
        statusPanel.add(finalCurrentBotLabel);

        currentBotLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        currentBotLabel.setText("null");
        statusPanel.add(currentBotLabel);

        finalBotUptimeLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        finalBotUptimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        finalBotUptimeLabel.setText("Bot Uptime");
        statusPanel.add(finalBotUptimeLabel);

        currentBotUptime.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        currentBotUptime.setText("00:00:00");
        statusPanel.add(currentBotUptime);

        pauseBotButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        pauseBotButton.setText("Pause Bot");
        pauseBotButton.setEnabled(false);
        statusPanel.add(pauseBotButton);

        stopBotButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        stopBotButton.setText("Stop Bot");
        statusPanel.add(stopBotButton);

        finalAvailableBotsLabel.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        finalAvailableBotsLabel.setText("Available Bots");

        jComboBox1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(this.botManager.getAvailableBotClassNames()));

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton1.setText("Start Bot");

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .addComponent(finalStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(finalAvailableBotsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addComponent(finalStatusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finalAvailableBotsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(339, Short.MAX_VALUE))
        );

        tabPane.addTab("Control Panel", controlPanel);

        logTextPane.setEditable(false);
        logScrollPane.setViewportView(logTextPane);

        debugOptsPanel.setLayout(new java.awt.GridBagLayout());

        finalLogLevelLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        finalLogLevelLabel.setText("Log Level");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        debugOptsPanel.add(finalLogLevelLabel, gridBagConstraints);

        logLevelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FINEST", "FINER", "FINE", "INFO", "WARNING", "SEVERE", "ALL" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        debugOptsPanel.add(logLevelComboBox, gridBagConstraints);

        showDebugOverlayCheckBox.setText("Show Debug Overlay");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        debugOptsPanel.add(showDebugOverlayCheckBox, gridBagConstraints);

        debugOptsScrollPane.setViewportView(debugOptsPanel);

        commandTextField.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        commandTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commandTextFieldActionPerformed(evt);
            }
        });

        executeCommandButton.setText("Execute");
        executeCommandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeCommandButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout debuggingPanelLayout = new javax.swing.GroupLayout(debuggingPanel);
        debuggingPanel.setLayout(debuggingPanelLayout);
        debuggingPanelLayout.setHorizontalGroup(
            debuggingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logScrollPane)
            .addComponent(debugOptsScrollPane)
            .addGroup(debuggingPanelLayout.createSequentialGroup()
                .addComponent(commandTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(executeCommandButton))
        );
        debuggingPanelLayout.setVerticalGroup(
            debuggingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(debuggingPanelLayout.createSequentialGroup()
                .addComponent(logScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(debuggingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(executeCommandButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(commandTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(debugOptsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabPane.addTab("Debugging", debuggingPanel);

        finalAppNameLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        finalAppNameLabel.setText("LeBrigand");

        finalVersionLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        finalVersionLabel.setText("Version:");

        versionLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        versionLabel.setText(lebrigand.App.VERSION);

        javax.swing.GroupLayout aboutPanelLayout = new javax.swing.GroupLayout(aboutPanel);
        aboutPanel.setLayout(aboutPanelLayout);
        aboutPanelLayout.setHorizontalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(finalAppNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(aboutPanelLayout.createSequentialGroup()
                        .addComponent(finalVersionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(versionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)))
                .addContainerGap())
        );
        aboutPanelLayout.setVerticalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(finalAppNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finalVersionLabel)
                    .addComponent(versionLabel))
                .addContainerGap(495, Short.MAX_VALUE))
        );

        tabPane.addTab("About", aboutPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void commandTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commandTextFieldActionPerformed
        System.out.println(evt.toString());
    }//GEN-LAST:event_commandTextFieldActionPerformed

    private void executeCommandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeCommandButtonActionPerformed
        System.out.println(evt.toString());
    }//GEN-LAST:event_executeCommandButtonActionPerformed

    private static TitledBorder makeTitledBorder(String borderText) {
        return javax.swing.BorderFactory.createTitledBorder(
                null,
                borderText,
                TitledBorder.DEFAULT_JUSTIFICATION,
                TitledBorder.DEFAULT_POSITION
        );
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewLeBrigandFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewLeBrigandFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewLeBrigandFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewLeBrigandFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewLeBrigandFrame(new BotManager(null, null)).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JTextField commandTextField;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel currentBotLabel;
    private javax.swing.JLabel currentBotUptime;
    private javax.swing.JPanel debugOptsPanel;
    private javax.swing.JScrollPane debugOptsScrollPane;
    private javax.swing.JPanel debuggingPanel;
    private javax.swing.JButton executeCommandButton;
    private javax.swing.JLabel finalAppNameLabel;
    private javax.swing.JLabel finalAvailableBotsLabel;
    private javax.swing.JLabel finalBotUptimeLabel;
    private javax.swing.JLabel finalCurrentBotLabel;
    private javax.swing.JLabel finalLeBrigandUptimeLabel;
    private javax.swing.JLabel finalLogLevelLabel;
    private javax.swing.JLabel finalStatusLabel;
    private javax.swing.JLabel finalVersionLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel leBrigandUptimeLabel;
    private javax.swing.JComboBox<String> logLevelComboBox;
    private javax.swing.JScrollPane logScrollPane;
    private javax.swing.JTextPane logTextPane;
    private javax.swing.JButton pauseBotButton;
    private javax.swing.JCheckBox showDebugOverlayCheckBox;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JButton stopBotButton;
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JLabel versionLabel;
    // End of variables declaration//GEN-END:variables
}
